### ISSUE TITLE
Node v0.7

### ISSUE THREAD

**Issue by jodal** [magnars/autolint#11]
autolint is currently locked to Node v0.6. If there isn't any known problems with autolint on Node v0.7, the environment setting could maybe be changed from "~0.6" to ">=0.6"?

**Comment by magnars** [comment]
Yes indeed, that seems unnecessarily strict. Have you tested it with 0.7?

**Comment by jodal** [comment]
No, I haven't, but I wanted to test buster-coffee on 0.7 using Travis CI, but it failed on autolint not being installable on 0.7: http://travis-ci.org/#!/jodal/buster-coffee/jobs/1444828

You could change the `package.json`, use Travis CI to run the autolint test suite on 0.7, and if it works, make a release with a looser version range. At least, that's a lazy man's test of autolint on 0.7, which is far better than no test.

**Comment by magnars** [comment]
That's a bit too far over on the lazy side. I'm working on getting a linux VM up on this mac, so I can test on both 0.6 and 0.7. Did it first on my Windows VM, then realized buster doesn't work very well there yet. :-P

**Comment by magnars** [comment]
Just tested in v0.7.11 and it works fine, if you can live with a deprecation warning. I've pushed a new version to npm, and will fix the deprecation when 0.8 lands.

**Comment by jodal** [comment]
Works for me :-)
