### ISSUE TITLE
Location for autolint.json

### ISSUE THREAD

**Issue by plumlee** [magnars/autolint#2]
Not clear to me what 'your root' means for autolint.json - is that root of my ~, or root for autolint? Or can there be multiple config files on a per-directory basis?

**Comment by magnars** [comment]
`autolint` looks for the file in the current directory, so I usually place it at the root of
the project. But where ever you want to run the command from is fine.

Having a global config in ~ sound like a nice addition, I've added it to the todo-list. :-)

**Comment by magnars** [comment]
After some contemplation, I think each project should define its autolint.conf fully, to avoid issues of "it's working on my machine". So removed global config from todo-list.
