### ISSUE TITLE
Consider upgrading to latest jslint

### ISSUE THREAD

**Issue by magnars** [magnars/autolint#6]
The jslint API seems to be changing a lot, which is why I haven't upgraded it very often.

But the bundled version is missing `eqeq` which is a bummer. Also, we're still on a 0.1 version, so breaking stuff in the name of progress should be acceptable.

**Comment by cjohansen** [comment]
In the past I've used `eqeqeq: false` to ditch the silly "only triple equals" rule, but that didn't work (both eqeqeq and eqeq, in both the files and in the config file)

**Comment by magnars** [comment]
I guess I'm only reluctant because it will cause massive breakage. The ruleset has changed so much. But better get with the program and upgrade.

Think I'll switch from a .json config file to a proper node module at the same time.

**Comment by cjohansen** [comment]
Awesome. That was another thing I thought "would've been nice"

**Comment by magnars** [comment]
That being said, I don't agree with the triple equals being silly.  Just the fact that JS has an equals operator _that isn't transient_ is staggering.

I've personally lost several hours to a bug caused by it. The main problem? I had already considered the case. I had a test covering that case. And that test was passing. The evil twins still bit my head off.

**Type coercion is not your friend.** Don't let habit stand in the way of doing things better.

**Comment by magnars** [comment]
Fixed in upgrade to 1.0.0.
