### ISSUE TITLE
[feature request] Allow suppressing a specific message in a specific place

### ISSUE THREAD

**Issue by penartur** [magnars/autolint#9]
Let's assume for example I'm using bitwise operators in a specific function intentionally. Currently, autolint leaves me no choice but to ignore the entire file completely or to allow bitwise operators everywhere. Obviously, neither of the options is a good one.

It would be great if we could suppress the specific messages occuring in the specific lines or blocks of code, similar to [http://msdn.microsoft.com/en-us/library/441722ys.aspx](#pragma warning).

I understand that this is the major feature, that it will probably require a major refactoring of autolint and hence hardly will be implemented; just wanted to share my thoughts with the following generations.

**Comment by magnars** [comment]
Hi @penartur,

You can add this to your file:

```
/*jslint bitwise:true*/
```

Adding it to the top of the file will allow bitwise operators in the entire file, or you can add it to a single function:

```
function justHere() {
    /*jslint bitwise:true*/
    return 1 << 1;
}
```

:-)

**Comment by penartur** [comment]
Thank you! :)
Isn't it worth mention in a documentation?

**Comment by magnars** [comment]
Good point, thanks. :)

**Comment by penartur** [comment]
The related issue is that not everything could be configured in JSLint; it would be great to allow options to contain list of messages `jslint` should suppress.
E.g.

``` javascript
module.exports = {
    linter: 'jslint',
    linterOptions: {
        suppress: { unnecessary_use: true }
    }
}
```

or

``` javascript
"use strict";

var itWillBeStringifiedAndSentToBrowser = function () {
    /*suppress unnecessary_use: true */
    "use strict"; //so that the function will be executed in strict environment in browser
}
```

**Comment by magnars** [comment]
Adding file- or function-local suppress would mean reimplementing large parts of jslint. However, adding a global suppress list is fairly trivial - and some pretty useful functionality if you want to use jslint but don't agree with Crockford on every issue. Something like this:

```
module.exports = {
    suppress: [ "Unnecessary 'use strict'." ]
};
```

Would that do?

**Comment by penartur** [comment]
Actually, implementing local suppresses was pretty easy, it only involved four places:
[New token in line 972](https://github.com/magnars/autolint/pull/10/files#L0R972)
[New function in lines 2201 through 2232](https://github.com/magnars/autolint/pull/10/files#L0R2201)
[Three lines in the existing `directive` function, lines 2328 through 2330](https://github.com/magnars/autolint/pull/10/files#L0R2328)
[A single line 4049](https://github.com/magnars/autolint/pull/10/files#L0R4049)
Implementing the rest of the feature was harder (and involved more changes).

The problem is that JSLint author doesn't seem to use some public repository for their source code, so that all of my fixes apply only to your local copy; and it will probably be quite a pain to do the merge once a new original JSLint version will be released.

**Comment by penartur** [comment]
> Would that do?

I don't think so. JSLint returns a human-readable error message, with the params substituted; that means that, with your suggestion, user has to say what exact error messages (not kinds of error messages) they don't want to see (and, additionally, they have to say it globally). I doubt anyone will use such a feature.
That doesn't mean I insist on implementing it my way :)
